version: '3.2'
services:
  reverse-proxy:
    volumes:
      - ./nginx-config/prod/templates/:/etc/nginx/templates/
      - ./nginx-config/:/nginx-config/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
     - api
     - api-dev
  api:
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - DOMAIN=${DOMAIN}
      - NODE_PORT=${NODE_PORT}
  