version: '3.2'
services: 
  api:
    environment: 
      - HTTPS=true
      - DOMAIN=${DOMAIN}
    ports: 
      - "443:${NODE_PORT}"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  api-dev:
    build: ${PATH_API_DEV}
    command: nodemon app.js
    container_name: cranach-api-dev
    environment: 
      - HTTPS=true
      - DOMAIN=${DOMAIN}
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_INDICES_PREFIX=$ELASTIC_INDICES_PREFIX_DEV
      - API_USERNAME=$API_USERNAME
      - API_PASSWORD=$API_PASSWORD
    image: cranach-api-dev
    ports: 
      - "8443:${NODE_PORT}"
    volumes:
      - ${PATH_API}/src:/usr/src/app
      - /usr/src/app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
        - elasticsearch
    networks:
      - cranach-network

