version: '3.2'
services: 
  elk:
    build: ${PATH_ELK}
    container_name: cranach-elk
    image: cranach-elk
    volumes: 
      - ./esdata:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  api:
    build: ${PATH_API}
    command: nodemon server.js
    container_name: cranach-api
    image: cranach-api
    ports: 
      - "8080:8080"
    volumes:
      - ${PATH_API}/src:/usr/src/app
      - /usr/src/app/node_modul