version: '3.2'
services: 
  elk:
    build: ${PATH_ELK}
    container_name: cranach-elk
    image: cranach-elk
    volumes: 
      - ./esdata:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - cranach-network
  api:
    build: ${PATH_API}
    command: nodemon app.js
    container_name: cranach-api
    environment: 
      - NODE_PORT=${NODE_PORT}
    image: cranach-api
    ports: 
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ${PATH_API}/src:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
        - elk
    networks:
      - cranach-network

networks: 
  cranach-network:
    driver: bridge
