version: '3.2'
services: 
  elk:
    build: ${PATH_ELK}
    image: cranach-elk
    volumes: 
      - ./esdata:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  api:
    build: ${PATH_API}
    image: cranach-api
    ports: 
      - "8080"
volumes: 
  esdata:
    driver: local
      