version: '3.2'
services:
  reverse-proxy:
    volumes:
      - ./nginx-config/prod/templates/:/etc/nginx/templates/
      - ./nginx-config/:/nginx-config/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
     - api
     - api-dev
  api:
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - DOMAIN=${DOMAIN}
      - NODE_PORT=${NODE_PORT}
  api-dev:
    build: ${PATH_API_DEV}
    command: nodemon app.js
    container_name: cranach-api-dev
    restart: unless-stopped
    environment: 
      - DOMAIN=${DOMAIN}
      - NODE_PORT=${NODE_PORT}
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_INDICES_PREFIX=$ELASTIC_INDICES_PREFIX_DEV
      - API_USERNAME=$API_USERNAME
      - API_PASSWORD=$API_PASSWORD
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
    image: cranach-api-dev
    volumes:
      - ${PATH_API_DEV}/src:/usr/src/app
      - /usr/src/app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
        - elasticsearch
    networks:
      - cranach-network

