global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    server: ${DOMAIN}

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - 'alert.rules.yml' 

scrape_configs:

  - job_name: 'api'
    static_configs:
      - targets: ['cranach-api:8080']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']