name: Deploy on remote server
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs: 
  build:
    name: build image and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: ${{ secrets.REMOTE_DIR }}cranach-docker
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
    - name: docker compose stop via SSH
      uses: appleboy/ssh-action@master
      with:
        script: |
          cd ${{ secrets.REMOTE_DIR }}cranach-docker &&
          docker compose stop
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}  
    - name: docker compose up -d via SSH
      uses: appleboy/ssh-action@master
      with:
        script: |
          cd ${{ secrets.REMOTE_DIR }}cranach-docker &&
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
